---
title: "MessAround"
output: html_document
date: "2023-06-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Git Commands
# git config --list
# use_git_config(user.name = "g2keating", user.email = "gkeating@uci.edu")
# git pull 
# git add .
# git commit -m ""
# git push
```

```{r}
unique(out1$V1)
print((sort(unique(result.long$matched_name2))))

(sort(unique(result.long$matched_name2)))
```

```{r}
bold_seqspec(taxon='Osmia')
```

```{r}
for (i in sort(unique(result.long$matched_name2))) { 
  foo<-bold_seqspec(i) # i<-"Lepidozona radians"
  out[i]<-nrow(foo)
  
  foot<- bold_seqspec('Lepidozona radians')
  out2['Lepidozona radians'] <- nrow(foot) 
  
```


```{r}
listtest <- unique(result.long$matched_name2)
SpeciesList <- c("Apodida","Aoroides", "Ancistrosyllis", "Aricidea", "Amphipholis" )
OneList <- "Aphelochaeta"

Starfish = bold_seqspec("Aphelochaeta")

write.csv(Starfish, "Starfish.csv")
```


```{r}
test_df <- lapply(SpeciesList, function(x){
  print(x)
  dfdf = bold_seqspec(x)
  dfdf<-dfdf %>% 
      mutate(Locus = case_when(

        str_detect(marker_codes %>% tolower(),"coi")~"COI", #Mitochondrial
        str_detect(marker_codes %>% tolower(),"co1")~"COI", #Mitochondrial
        str_detect(markercode %>% tolower(),"coi")~"COI",#Mitochondrial
        str_detect(markercode %>% tolower(),"co1")~"COI",#Mitochondrial
        str_detect(markercode %>% tolower(),"coxiii")~"COI", #Mitochondrial
        str_detect(marker_codes %>% tolower(),"coxiii")~"COI", #Mitochondrial
        T~"Other"))%>%
      filter(Locus!="Other")
    
    xdf<-tibble(FinalID=x,
                BOLD_Records=nrow(dfdf),
                BOLD_Records_USA=sum(dfdf$country=="United States", na.rm=T),
                BOLD_Records_CA=sum(dfdf$province_state=="California", na.rm=T),

      
                #COI, mitochondrial
                BOLD_Records_COI=sum(dfdf$Locus=="COI", na.rm = T),
                BOLD_Records_COI_USA=sum(dfdf$Locus=="COI" & dfdf$country=="United States", na.rm=T),
                BOLD_Records_COI_CA=sum(dfdf$Locus=="COI" &dfdf$province_state=="California", na.rm=T),
                BOLD_Records_COI_SW = sum( dfdf$Locus=="COI" &dfdf$province_state %in% c("California","Arizona", "New Mexico", "Texas", "Nevada", "Utah", "Colorado"), na.rm=T),
                
               
    )
  
  
}
  ) %>% bind_rows()
```


```{r}
test_df <- lapply(OneList, function(x){
  print(x)
  dfdf = bold_seqspec(x)
  dfdf<-dfdf %>% 
      mutate(Locus = case_when(

        str_detect(marker_codes %>% tolower(),"coi")~"COI", #Mitochondrial
        str_detect(marker_codes %>% tolower(),"co1")~"COI", #Mitochondrial
        str_detect(markercode %>% tolower(),"coi")~"COI",#Mitochondrial
        str_detect(markercode %>% tolower(),"co1")~"COI",#Mitochondrial
        str_detect(markercode %>% tolower(),"coxiii")~"COI", #Mitochondrial
        str_detect(marker_codes %>% tolower(),"coxiii")~"COI", #Mitochondrial
        T~"Other"))%>%
      filter(Locus!="Other")
    
    xdf<-tibble(FinalID=x,
                BOLD_Records=nrow(dfdf),
                BOLD_Records_USA=sum(dfdf$country=="United States", na.rm=T),
                BOLD_Records_CA=sum(dfdf$province_state=="California", na.rm=T),

      
                #COI, mitochondrial
                BOLD_Records_COI=sum(dfdf$Locus=="COI", na.rm = T),
                BOLD_Records_COI_USA=sum(dfdf$Locus=="COI" & dfdf$country=="United States", na.rm=T),
                BOLD_Records_COI_CA=sum(dfdf$Locus=="COI" &dfdf$province_state=="California", na.rm=T),
                BOLD_Records_COI_SW = sum( dfdf$Locus=="COI" &dfdf$province_state %in% c("California","Arizona", "New Mexico", "Texas", "Nevada", "Utah", "Colorado"), na.rm=T),
                
               
    )
  
  
}
  ) %>% bind_rows()

```



```{r}
testlist <- taxa2[duplicated(taxa2$species_name), ]

my_data[!duplicated(my_data$Sepal.Width), ]
```



```{r}

check<-bold_search(sci = "Acarnus erithacus")

result.long <- result.long[1:100,]

taxa2<-sort(unique(result.long$matched_name2))

out<-list()
for (i in taxa2) { # i<-"Ancistrosyllis"
  foo<-bold_search(sci=i)
  if(length(foo)>1) {out[i]<-foo$tax_rank}
  print(out[i])
  }

test2 <- t(test)

data2 <- rownames_to_column(test2, "names")


test <- data.frame(out)

test2 <- data.frame(test2)

species.fail<-data.frame(setdiff(unique(result.long$matched_name2), unique(data2$names)))

data2$names

```

```{r}

test<-list()
waste<-list()

test<-data.frame()

rows_append()

test %>% add_column(fun)


bind_rows(test, fun_test)


for(j in fun_test){
  test[j] 
  
}
  


for (i in fun_test) { # i<-"Ancistrosyllis"
  foo<-bold_search(sci=i)
  if(length(foo)>2) 
    {test[i,]<- bind_rows(foo)}
}



for (i in lst_tol) { # i<-"Ancistrosyllis"
  foo<-bold_search(sci=i)
  if(length(foo)>2) 
    {out[i]<-foo$tax_rank}
  else 
    {bad[i] <- lst_tol[i]}
  print(out[i])
}

fun_test<- c("Acanthinucella paucilirata", "Ancistrosyllis", "Acarnus erithacus","Acanthinucella")


check<-bold_search(sci = "Acanthinucella paucilirata")
check<-bold_search(sci = "Ancistrosyllis")
check<-bold_search(sci = "Acarnus erithacus")
check<-bold_search(sci = "Acanthinucella")


l = "Acanthinucella"
check<-bold_search(sci = l )

out = rbind(out, check)
```



```{r}
bad<-list()
out<-data.frame(rbind(1:8))
```


```{r}
rint(x)
  mydf=bold_seqspec(x) 
  if(class(mydf)=="data.frame"){ 
    bldlength <- nrow(mydf) %>%
    bdf <- mydf %>% 
    mydf<-mydf %>% 
      mutate(Locus = case_when(

        str_detect(marker_codes %>% tolower(),"coi")~"COI", #Mitochondrial
        str_detect(marker_codes %>% tolower(),"co1")~"COI", #Mitochondrial
        str_detect(markercode %>% tolower(),"coi")~"COI",#Mitochondrial
        str_detect(markercode %>% tolower(),"co1")~"COI",#Mitochondrial
        str_detect(markercode %>% tolower(),"coxiii")~"COI", #Mitochondrial
        str_detect(marker_codes %>% tolower(),"coxiii")~"COI", #Mitochondrial
        T~"Other"))%>%
      filter(Locus!="Other")
    
    xdf<-tibble(FinalID=x,
                BOLD_Records= bldlength,
                BOLD_Records_USA=sum(bdf$country=="United States", na.rm=T),
                BOLD_Records_CA=sum(bdf$province_state=="California", na.rm=T),

      
                #COI, mitochondrial
                BOLD_Records_COI=sum(mydf$Locus=="COI", na.rm = T),
                BOLD_Records_COI_USA=sum(mydf$Locus=="COI" & mydf$country=="United States", na.rm=T),
                BOLD_Records_COI_CA=sum(mydf$Locus=="COI" &mydf$province_state=="California", na.rm=T),
                BOLD_Records_COI_SW = sum( mydf$Locus=="COI" &mydf$province_state %in% c("California","Arizona", "New Mexico", "Texas", "Nevada", "Utah", "Colorado"), na.rm=T),
                
    )}
```



```{r}
identical()

length(unique(Arthro_taxa$Taxon))
length(unique(taxa_table_gnr$user_supplied_name))


lsttest <- Arthro_taxa$Taxon

lsttest2 <- taxa_table_gnr$user_supplied_name


lstmissing <- setdiff(lsttest,lsttest2)

setdiff(lsttest2,lsttest)


missing_gnr <-gnr_resolve(sci = as.character(lstmissing), data_source_ids = c(11), with_canonical_ranks=T)

missing_tol2 <- tol_resolve(lstmissing, include_suppressed = T)

missing_res <- resolve(lstmissing)

test <- as.data.frame(missing_res)

length(unique(test$gnr.user_supplied_name))

y <- gnr_resolve(sci = lstmissing)

q <- resolve("armadillidiidae ")

q <- as.data.frame(q)

f <- gnr_resolve("armadillidiidae")

t <- resolve(lstmissing)

t<- as.data.frame(t)

z <- gnr_resolve(sci = "armadillidiidae ", data_source_ids = c(12), with_canonical_ranks=T)

x <-gnr_datasources()

missing_gnr <-gnr_resolve(sci = as.character(lstmissing), data_source_ids = c(12), with_canonical_ranks=T)

x <- gnr_resolve(sci = c(lstmissing), with_context = T, with_canonical_ranks = T, best_match_only = T,cap_first = T)

r <- gnr_resolve(sci = c("Hahnidae","Armadillidiidae","Arctitalitus","Cybocephalidae","Patapus","Amblyoponinae","Cerapachyinae","Ecitoninae","Ponerinae","Proceratiinae","Pseudomyrmecinae"), with_context = T, with_canonical_ranks = T, best_match_only = T)


r <- gnr_resolve(lstmissing, best_match_only = T, canonical = T)

r <- gnr_resolve("Hahnidae", best_match_only = T, canonical = T)

```


```{r}
length(unique(taxa_table_gnr$user_supplied_name))

length(unique(taxa_table_gnr2$user_supplied_name))

diff <- setdiff(taxa_table_gnr$user_supplied_name, taxa_table_gnr2$user_supplied_name)

diff2 <- setdiff(taxa_table_gnr2$user_supplied_name, taxa_table_gnr$user_supplied_name)


diff <- as.data.frame(diff)

```


```{r}
taxa_table_GBIF <-gnr_resolve(sci = as.character(lst), data_source_ids = c(11), with_canonical_ranks=T)

taxa_table_gnr <-gnr_resolve(sci = as.character(lst), best_match_only = T, with_canonical_ranks=T)

diffGBIF <- as.data.frame(setdiff(taxa_table_GBIF$user_supplied_name, taxa_table_gnr$user_supplied_name))

diffAll <- as.data.frame(setdiff(taxa_table_gnr$user_supplied_name, taxa_table_GBIF$user_supplied_name))

MissingTaxa1 <-setdiff(Arthro_taxa$Taxon, taxa_table_GBIF$user_supplied_name)

MissingTaxa2 <-setdiff(Arthro_taxa$Taxon, taxa_table_gnr$user_supplied_name)

x <- intersect(MissingTaxa1,MissingTaxa2)

z <- tol_resolve(x)

diffGBIF <- as.data.frame(setdiff(taxa_table_GBIF, taxa_table_gnr))

diffGBIF <- setdiff(taxa_table_GBIF$user_supplied_name, taxa_table_gnr$user_supplied_name)


diffGBIF

q <- taxa_table_GBIF %>% filter(taxa_table_GBIF$user_supplied_name == c("Tulbergiidae",    "Sminthurididiae", "Laemophloeidea",  "Ochodaeida",      "Clastropteridae", "Scutellaridae",   "Myrmecosystus" ))


w <- taxa_table_GBIF %>% filter(taxa_table_GBIF$user_supplied_name == c("Tulbergiidae","Sminthurididiae"))

t <- taxa_table_GBIF %>% filter(taxa_table_GBIF$user_supplied_name == c("Tulbergiidae"))

j <- taxa_table_GBIF %>% filter(taxa_table_GBIF$user_supplied_name == c("Sminthurididiae"))


b <- taxa_table_GBIF %>% filter(taxa_table_GBIF$user_supplied_name == c("Clastropteridae","Sminthurididiae"))

```


```{r}
rotl::tnrs_contexts()
```





```{r}
Arthro_Rafi <- read_csv("Arthro_Rafi.csv")




Missing_Bold_Taxa <- arthro_taxa_final %>% 
  filter(is.na(taxon))

Missing_seqspec <- Arthro_Rafi %>% 
  filter(is.na())


check2<-bold_search(sci = "Vostox apicedentatus")

check4<-bold_seqspec("Blackfordia virginica")

check4<-bold_seqspec("Atherinops")

Atherinops

```

```{r}
Arthro_Gap_analysis2 <- read_csv("Arthro_Gap_analysis2.csv")
```
```{r}
# Taxa_working <- Taxa_working[1:60,]

library(rotl)
library(knitr)

Taxa_test <- taxa_table[1:100,]


taxon_search <- tnrs_infer_context(taxa_table$Species_ed)

kable(taxon_search)

taxon_search <- tnrs_match_names(names = Taxa_test$Species_ed, context_name = "All life")


taxon_search$context_name

as.data.frame(taxon_search)
```




```{r}

fart  <- c( "Tetracanthella brachyura", "Tephritis brachyura", "Synallaxis brachyura",  "Urochloa brachyura")



bold_df_summary<-  lapply(unique(fart), function(x){
  print(x)
  mydf=bold_seqspec(x)
  bdf=mydf
  bldlength = nrow(mydf)
  if(class(mydf)=="data.frame" && colnames(mydf[1]) == "processid"){ 
    mydf<- mydf %>% 
      mutate(Locus = case_when(
        
        str_detect(marker_codes %>% tolower(),"coi")~"COI", #Mitochondrial
        str_detect(marker_codes %>% tolower(),"co1")~"COI", #Mitochondrial
        str_detect(markercode %>% tolower(),"coi")~"COI",#Mitochondrial
        str_detect(markercode %>% tolower(),"co1")~"COI",#Mitochondrial
        str_detect(markercode %>% tolower(),"coxiii")~"COI", #Mitochondrial
        str_detect(marker_codes %>% tolower(),"coxiii")~"COI", #Mitochondrial
        T~"Other"))
    
    xdf<-tibble(FinalID=x,
                phylum = first(mydf$phylum_name),
                class = first(mydf$class_name),
                order = first(mydf$order_name),
                family = first(mydf$family_name),
                genus = first(mydf$genus_name),
                BOLD_Records= bldlength,
                BOLD_Records_USA=sum(bdf$country=="United States", na.rm=T),
                BOLD_Records_CA=sum(bdf$province_state=="California", na.rm=T),
                
                
                #COI, mitochondrial
                BOLD_Records_COI=sum(mydf$Locus=="COI", na.rm = T),
                BOLD_Records_COI_USA=sum(mydf$Locus=="COI" & mydf$country=="United States", na.rm=T),
                BOLD_Records_COI_CA=sum(mydf$Locus=="COI" &mydf$province_state=="California", na.rm=T),
                BOLD_Records_COI_SW = sum( mydf$Locus=="COI" &mydf$province_state %in% c("California","Arizona", "New Mexico", 
                                                                                         "Texas", "Nevada", "Utah", "Colorado"), na.rm=T),
                
    )
  }
  else  {
    xdf= tibble(FinalID=x,  
                BOLD_Records=0, BOLD_Records_USA=0, BOLD_Records_CA=0, BOLD_Records_SW = 0,
                BOLD_Records_ITS=0, BOLD_Records_ITS_USA=0, BOLD_Records_ITS_CA=0, BOLD_Records_ITS_SW = 0,
                BOLD_Records_COI=0, BOLD_Records_COI_USA=0, BOLD_Records_COI_CA=0, BOLD_Records_COI_SW = 0,
                BOLD_Records_CYTB=0, BOLD_Records_CYTB_USA=0, BOLD_Records_CYTB_CA=0, BOLD_Records_CYTB_SW = 0,
                BOLD_Records_12S=0, BOLD_Records_12S_USA=0, BOLD_Records_12S_CA=0, BOLD_Records_12S_SW = 0,
                BOLD_Records_16S=0, BOLD_Records_16S_USA=0, BOLD_Records_16S_CA=0, BOLD_Records_16S_SW = 0,
                BOLD_Records_18S=0, BOLD_Records_18S_USA=0, BOLD_Records_18S_CA=0, BOLD_Records_18S_SW = 0,
                phylum = NA,
                class = NA,
                order = NA,
                family = NA,
                genus = NA)
  }
  xdf
})  %>% bind_rows()

```

```{r}

detach("package:rotl", unload = T)

x <- c( "Leptopecten latiauratus", "Uromunna ubiquita", "Lucinisca nuttalli",  "Vitreolina columbiana", "Volvulella cylindrica")
tax_missing <- tax_rank(x, db ="gbif", rows =)

z <- tax_rank(x, db = "gbif", rows = 1)

```

```{r}
#Git Commands
# git config --list
# use_git_config(user.name = "g2keating", user.email = "gkeating@uci.edu")
# git pull 
# git add .
# git commit -m ""
# git push
```


